### ISSUE TITLE
mkdocs-toc-plugin里面utils.py类型注释报错

### ISSUE THREAD

**Issue by mikigo** [TonyCrane/mkdocs-toolchain#1]
报错：TypeError: 'type' object is not subscriptable

![image](https://github.com/TonyCrane/mkdocs-toolchain/assets/47137003/3b7da57f-9d45-4a66-8985-b8032972b4f1)

我的环境是 Python 3.7

这三个函数的返回类型注释有问题:

```python
def _words_count(markdown: str) -> tuple[int, int, int]:
   ...

def _split_markdown(markdown: str) -> tuple[str, str, list]:
    ...

def _clean_markdown(markdown: str) -> tuple[str, list]:
    ...
```

建议换成：

```python
from typing import Tuple

def _words_count(markdown: str) -> Tuple[int, int, int]:
   ...

def _split_markdown(markdown: str) -> Tuple[str, str, list]:
    ...

def _clean_markdown(markdown: str) -> Tuple[str, list]:
    ...
```

修改之后就正常了：

![image](https://github.com/TonyCrane/mkdocs-toolchain/assets/47137003/bb4ebceb-cce8-4ca3-a19b-a67fd417df3e)

**Comment by TonyCrane** [comment]
3.7 太老了（
