### ISSUE TITLE
mkdocs-toc-plugin

### ISSUE THREAD

**Issue by selfknoww** [TonyCrane/mkdocs-toolchain#3]
刚发现从 pypi 中下架了，请问 mkdocs-toc-plugin 插件还能用吗？之前用过感觉很方便，如果不能用那就打扰了qwq

**Comment by TonyCrane** [comment]
能用，要用的话自己从源码安装 (pip install .)

之前 pypi 那个是其他人未经我同意私自上传的，所以删除了

没发布到 pypi 上的插件都是个人性很强而且没经调试的，想用的话就从源码装

**Comment by selfknoww** [comment]
好的 Thanks♪(･ω･)ﾉ
